apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-nodes-viewer
  labels:
    # These labels are used by the Argo CD operator to aggregate roles, if applicable
    # argocd/aggregate-to-controller: "true" 
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-nodes-viewer-binding
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: argo-cd
roleRef:
  kind: ClusterRole
  name: argocd-nodes-viewer
  apiGroup: rbac.authorization.k8s.io
